---

- name: Добавление зеркала яндекса в репозитории
  hosts: elastic
  become: yes
  vars:
    elastic_key: /etc/elasticsearch/certs/http_ca.crt
    elastic_password_file: /root/elastic-password.txt
  tasks:
   - name: Добавляет репо
     apt_repository:
      repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" ## Пусть будет ключей, верим яндексу
      filename: "elactic-7-yandex"
   
   - name: Обновить пакеты
     apt:
      update_cache: yes

   - name: Установить Elasticsearch
     apt:
      name: elasticsearch
      state: present

   - name: Создать конфигурацию elasticsearch.yml (без аутентификации)  ## Отключение хпак чтобы без пароля 
     copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: 0644
        content: |
          cluster.name: my-cluster
          node.name: node-1
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          xpack.security.http.ssl.enabled: false
     notify: restart elasticsearch

   - name: Автозапуск +  включение 
     systemd:
      name: elasticsearch
      state: started
      enabled: yes

   - name: Ждать пока запустится порт 
     wait_for:
      port: 9200
      delay: 10
      timeout: 60

   - name: Проверить состояние кластера
     command: >
      curl http://localhost:9200/_cluster/health?pretty
     register: cluster_health
     changed_when: false
     ##ВЫВЕСТИ ТОКЕН ДЛЯ КИБАНЫ

   - name: Показать статус кластера
     debug:
        msg: |
         "{{ cluster_health.stdout }}"
#         "{{ reset_pwd.stdout }}"
     
  handlers:
    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        






















  #  - name: Сбросить пароль elastic
  #    command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -b
  #    register: reset_pwd
  #    changed_when: "'New value' in reset_pwd.stdout"

  #  - name: Сохранить пароль в файл
  #    copy:
  #     content: "{{ reset_pwd.stdout }}"
  #     dest: "{{ elastic_password_file }}"
  #     owner: root
  #     group: root
  #     mode: '0600'

        # curl -u elastic:{{ reset_pwd.stdout_lines[-1] }}
        # --cacert {{ elastic_key }}