---

- name: Установка Filebeat
  hosts: web
  become: yes
  tasks:
    - name: Добавляет репо ##Оказывается нету кибаны в этой убунте
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" ## Пусть будет ключей, верим яндексу
        filename: "elactic-7-yandex"
        update_cache: yes
    # - name: Обновить пакеты
    #   apt:
    #     update_cache: yes
        
    - name: Установить Filebeat
      apt:
        name: filebeat
        state: present
   
    - name: Включить модуль Nginx в Filebeat  ## Включает  модуль 
      command: filebeat modules enable nginx
      args:
        creates: /etc/filebeat/modules.d/nginx.yml
      register: module_enabled
      changed_when: module_enabled.rc == 0

    - name: Скопировать конфигурацию filebeat.yml ## Настройки для подключения автоматом
      template:
          src: ../templates/filebeat.yml.j2
          dest: /etc/filebeat/filebeat.yml
          owner: root ##  не запускается  если не владелец рут
          group: root
          mode: 0644
      notify: restart filebeat
   
  handlers:   ## Просто перезапуск
    - name: restart filebeat
      service:
        name: filebeat
        state: restarted