---

- name: Установка Kibana
  hosts: kibana
  become: yes
  tasks:
    - name: Добавляет репо ##Оказывается нету кибаны в этой убунте
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" ## Пусть будет ключей, верим яндексу
        filename: "elactic-7-yandex"
    - name: Обновить пакеты
      apt:
        update_cache: yes
    - name: Установить Kibana
      apt:
        name: kibana
        state: present

    - name: Сконфигурировать kibana.yml  ## Подключение к эластику
      copy:
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: 0644
        content: |
          server.name: kibana
          server.host: "0.0.0.0"
          server.port: 5601
          elasticsearch.hosts: ["http://{{ elasticsearch_host | default('localhost') }}:9200"]
          monitoring.ui.container.elasticsearch.enabled: true
      notify: restart kibana 

    - name: Включить и запустить сервис Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes
  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted