---

- name: Установка Kibana
  hosts: kibana
  become: yes
  tasks:
    - name: Добавляет репо ##Оказывается нету кибаны в этой убунте
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" ## Пусть будет ключей, верим яндексу
        filename: "elactic-7-yandex"
    - name: Обновить пакеты
      apt:
        update_cache: yes
    - name: Установить Kibana
      apt:
        name: kibana
        state: present

    - name: Включить и запустить сервис Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes